DROP TABLE STAT_NOM.ITF_LOKBRIG_SVERKA CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE STAT_NOM.ITF_LOKBRIG_SVERKA
(
  KOD_DOR    NUMBER(2),
  DEPO_MM    NUMBER(4),
  NOM_MM     NUMBER(10),
  KPZ        NUMBER(4),
  DATE_OP    DATE,
  DATE_CALC  DATE,
  KOP        NUMBER(6),
  OZN_MM     NUMBER(1),
  PR_TAKS    NUMBER(1),
  OZN_DEL    NUMBER(1),
  DATE_INF   DATE
)
ON COMMIT DELETE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE;

COMMENT ON TABLE STAT_NOM.ITF_LOKBRIG_SVERKA IS '%Є.093616.2.01.01.0.001  001.000.000%Придн%Панко О. В.% Перелік документів, збережених в АСУ ЛокБриг';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.KOD_DOR IS 'Код регіональної філії';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.DEPO_MM IS 'Депо приписки бригади';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.NOM_MM IS 'Номер маршруту';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.KPZ IS 'Депо передачі інформації';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.DATE_OP IS 'Дата передачі інформації (формат dd.mm.yyyy)';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.DATE_CALC IS 'Дата створення документу в АСУ ЛокБриг (формат dd.mm.yyyy)';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.KOP IS 'Табельний номер оператора ТЧУ';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.OZN_MM IS 'Тип маршруту (0- поїзний з ТРО; 1, 2, 5, 6 - зарплатний)';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.PR_TAKS IS 'Ознака таксування в ТЧУ Локбриг (1- так, 0- ні)';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.OZN_DEL IS 'признак видалення маршруту (1- так, 0- ні)';

COMMENT ON COLUMN STAT_NOM.ITF_LOKBRIG_SVERKA.DATE_INF IS 'Дата обробки інформації в БД АСК ВП УЗ-Є ';



CREATE OR REPLACE SYNONYM MSG_WORK.S_ITF_LOKBRIG_SVERKA FOR STAT_NOM.ITF_LOKBRIG_SVERKA;


GRANT DELETE, INSERT, SELECT, UPDATE ON STAT_NOM.ITF_LOKBRIG_SVERKA TO APPL_DBW;

GRANT DELETE, INSERT, SELECT, UPDATE ON STAT_NOM.ITF_LOKBRIG_SVERKA TO MSG_WORK;

GRANT DELETE, INSERT, SELECT, UPDATE ON STAT_NOM.ITF_LOKBRIG_SVERKA TO SUVP_POTOK;

GRANT DELETE, INSERT, SELECT, UPDATE ON STAT_NOM.ITF_LOKBRIG_SVERKA TO SUVP_POTOK_SPR;
