select e.KOD_MESS, e.KOD_ERR, e.KOD_OBR, e.PR_MOD, e.subtype, e.DATE_BEG, MM.DATE_OP, e.ESR_OP, 
e.IDF_EVENT, e.ID_1, e.ID_2, e.ID_3,
MM.TYPE_MM, MM.JAVKA, MM.IDF_MM, MM.NOM_MRM, MM.DEPO, MM.DATE_MM, MM.DATE_CALC,
MSG.TEXT_MESS, MSG.TEXT_DIAGN
from EVENT.EV_ALL_EVENTS e
join EVENT.VW_MESS_TXT MSG on e.IDF_EVENT = MSG.IDF_EVENT
left join MD_MM.SREZ_ACTUAL_MM MM on e.IDF_EVENT = MM.IDF_MOD 
join ASKVP_VIEW.V_DIC_DEPO DEPO on (e.ID_2 = DEPO.ID_DEPO)
where e.IDF_EVENT = 4687171296
